wallpaper {
    monitor = eDP-1
    path = /home/miguel/Projects/wallpaper/dragon.png
}
#preload = /home/miguel/Projects/wallpaper/dragon.png
#wallpaper = , /home/miguel/Projects/wallpaper/dragon.png
